# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170628_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stud_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pictures/'),
        ),
    ]
