# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_student_stud_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_pic',
            field=models.ImageField(default='pictures/None/profile.jpg', upload_to='pictures/'),
        ),
    ]
