# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20170628_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_pic',
            field=models.ImageField(default='myapp/pictures/None/profile.jpg', upload_to='myapp/pictures/'),
        ),
    ]
