# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20170628_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
    ]
