# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_pagehitcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagehitcount',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
